In [4]:
import pandas as pd

file_path = "../data/raw/MachineLearningCSV/MachineLearningCVE/Monday-WorkingHours.pcap_ISCX.csv"

df = pd.read_csv(file_path)

df.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,49188,4,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,49188,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,49188,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,49188,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,49486,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [5]:
df.columns.tolist()

[' Destination Port',
 ' Flow Duration',
 ' Total Fwd Packets',
 ' Total Backward Packets',
 'Total Length of Fwd Packets',
 ' Total Length of Bwd Packets',
 ' Fwd Packet Length Max',
 ' Fwd Packet Length Min',
 ' Fwd Packet Length Mean',
 ' Fwd Packet Length Std',
 'Bwd Packet Length Max',
 ' Bwd Packet Length Min',
 ' Bwd Packet Length Mean',
 ' Bwd Packet Length Std',
 'Flow Bytes/s',
 ' Flow Packets/s',
 ' Flow IAT Mean',
 ' Flow IAT Std',
 ' Flow IAT Max',
 ' Flow IAT Min',
 'Fwd IAT Total',
 ' Fwd IAT Mean',
 ' Fwd IAT Std',
 ' Fwd IAT Max',
 ' Fwd IAT Min',
 'Bwd IAT Total',
 ' Bwd IAT Mean',
 ' Bwd IAT Std',
 ' Bwd IAT Max',
 ' Bwd IAT Min',
 'Fwd PSH Flags',
 ' Bwd PSH Flags',
 ' Fwd URG Flags',
 ' Bwd URG Flags',
 ' Fwd Header Length',
 ' Bwd Header Length',
 'Fwd Packets/s',
 ' Bwd Packets/s',
 ' Min Packet Length',
 ' Max Packet Length',
 ' Packet Length Mean',
 ' Packet Length Std',
 ' Packet Length Variance',
 'FIN Flag Count',
 ' SYN Flag Count',
 ' RST Flag Count',
 ' PSH Flag Count',
 ' ACK Flag Count',
 ' URG Flag Count',
 ' CWE Flag Count',
 ' ECE Flag Count',
 ' Down/Up Ratio',
 ' Average Packet Size',
 ' Avg Fwd Segment Size',
 ' Avg Bwd Segment Size',
 ' Fwd Header Length.1',
 'Fwd Avg Bytes/Bulk',
 ' Fwd Avg Packets/Bulk',
 ' Fwd Avg Bulk Rate',
 ' Bwd Avg Bytes/Bulk',
 ' Bwd Avg Packets/Bulk',
 'Bwd Avg Bulk Rate',
 'Subflow Fwd Packets',
 ' Subflow Fwd Bytes',
 ' Subflow Bwd Packets',
 ' Subflow Bwd Bytes',
 'Init_Win_bytes_forward',
 ' Init_Win_bytes_backward',
 ' act_data_pkt_fwd',
 ' min_seg_size_forward',
 'Active Mean',
 ' Active Std',
 ' Active Max',
 ' Active Min',
 'Idle Mean',
 ' Idle Std',
 ' Idle Max',
 ' Idle Min',
 ' Label']

In [8]:
df[" Label"].value_counts()

 Label
BENIGN    529918
Name: count, dtype: int64

In [11]:
df.isnull().sum()

 Destination Port              0
 Flow Duration                 0
 Total Fwd Packets             0
 Total Backward Packets        0
Total Length of Fwd Packets    0
                              ..
Idle Mean                      0
 Idle Std                      0
 Idle Max                      0
 Idle Min                      0
 Label                         0
Length: 79, dtype: int64

In [12]:
df.shape

(529918, 79)

In [13]:
import pandas as pd
import numpy as np

print("Notebook is working!")

Notebook is working!

In [15]:
numeric_df = df.select_dtypes(include=np.number)

np.isinf(numeric_df).sum().sum()

np.int64(810)

In [17]:
tuesday_path = "../data/raw/MachineLearningCSV/MachineLearningCVE/Tuesday-WorkingHours.pcap_ISCX.csv"

df_tuesday = pd.read_csv(tuesday_path)

df_tuesday.shape

(445909, 79)

In [19]:
df_tuesday[" Label"].value_counts()

 Label
BENIGN         432074
FTP-Patator      7938
SSH-Patator      5897
Name: count, dtype: int64

In [21]:
df_tuesday.isnull().sum().sum()

np.int64(201)

In [23]:
df_tuesday.duplicated().sum()

np.int64(24065)

In [25]:
numeric_tuesday = df_tuesday.select_dtypes(include=np.number)

np.isinf(numeric_tuesday).sum().sum()

np.int64(327)

In [27]:
import os
import pandas as pd
import numpy as np

folder = "../data/raw/MachineLearningCSV/MachineLearningCVE"

for file in os.listdir(folder):
    if file.endswith(".csv"):
        path = os.path.join(folder, file)
        data = pd.read_csv(path)

        numeric = data.select_dtypes(include=np.number)

        print("\n" + "=" * 70)
        print(file)
        print("Rows, Columns:", data.shape)
        print("Missing values:", data.isnull().sum().sum())
        print("Duplicate rows:", data.duplicated().sum())
        print("Infinite values:", np.isinf(numeric).sum().sum())
        print("\nLabels:")
        print(data[" Label"].value_counts())

======================================================================
Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
Rows, Columns: (225745, 79)
Missing values: 4
Duplicate rows: 2633
Infinite values: 64

Labels:
 Label
DDoS      128027
BENIGN     97718
Name: count, dtype: int64

======================================================================
Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
Rows, Columns: (286467, 79)
Missing values: 15
Duplicate rows: 72353
Infinite values: 727

Labels:
 Label
PortScan    158930
BENIGN      127537
Name: count, dtype: int64

======================================================================
Friday-WorkingHours-Morning.pcap_ISCX.csv
Rows, Columns: (191033, 79)
Missing values: 28
Duplicate rows: 6888
Infinite values: 216

Labels:
 Label
BENIGN    189067
Bot         1966
Name: count, dtype: int64

======================================================================
Monday-WorkingHours.pcap_ISCX.csv
Rows, Columns: (529918, 79)
Missing values: 64
Duplicate rows: 26935
Infinite values: 810

Labels:
 Label
BENIGN    529918
Name: count, dtype: int64

======================================================================
Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
Rows, Columns: (288602, 79)
Missing values: 18
Duplicate rows: 35630
Infinite values: 396

Labels:
 Label
BENIGN          288566
Infiltration        36
Name: count, dtype: int64

======================================================================
Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
Rows, Columns: (170366, 79)
Missing values: 20
Duplicate rows: 6066
Infinite values: 250

Labels:
 Label
BENIGN                        168186
Web Attack � Brute Force        1507
Web Attack � XSS                 652
Web Attack � Sql Injection        21
Name: count, dtype: int64

======================================================================
Tuesday-WorkingHours.pcap_ISCX.csv
Rows, Columns: (445909, 79)
Missing values: 201
Duplicate rows: 24065
Infinite values: 327

Labels:
 Label
BENIGN         432074
FTP-Patator      7938
SSH-Patator      5897
Name: count, dtype: int64

======================================================================
Wednesday-workingHours.pcap_ISCX.csv
Rows, Columns: (692703, 79)
Missing values: 1008
Duplicate rows: 81909
Infinite values: 1586

Labels:
 Label
BENIGN              440031
DoS Hulk            231073
DoS GoldenEye        10293
DoS slowloris         5796
DoS Slowhttptest      5499
Heartbleed              11
Name: count, dtype: int64

In [29]:
summary = []

for file in os.listdir(folder):
    if file.endswith(".csv"):
        path = os.path.join(folder, file)
        data = pd.read_csv(path)

        numeric = data.select_dtypes(include=np.number)

        summary.append({
            "File": file,
            "Rows": data.shape[0],
            "Columns": data.shape[1],
            "Missing": data.isnull().sum().sum(),
            "Duplicates": data.duplicated().sum(),
            "Infinite": np.isinf(numeric).sum().sum(),
            "Labels": ", ".join(data[" Label"].unique())
        })

summary_df = pd.DataFrame(summary)
summary_df

,File,Rows,Columns,Missing,Duplicates,Infinite,Labels
0,Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv,225745,79,4,2633,64,"BENIGN, DDoS"
1,Friday-WorkingHours-Afternoon-PortScan.pcap_IS...,286467,79,15,72353,727,"BENIGN, PortScan"
2,Friday-WorkingHours-Morning.pcap_ISCX.csv,191033,79,28,6888,216,"BENIGN, Bot"
3,Monday-WorkingHours.pcap_ISCX.csv,529918,79,64,26935,810,BENIGN
4,Thursday-WorkingHours-Afternoon-Infilteration....,288602,79,18,35630,396,"BENIGN, Infiltration"
5,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,170366,79,20,6066,250,"BENIGN, Web Attack � Brute Force, Web Attack �..."
6,Tuesday-WorkingHours.pcap_ISCX.csv,445909,79,201,24065,327,"BENIGN, FTP-Patator, SSH-Patator"
7,Wednesday-workingHours.pcap_ISCX.csv,692703,79,1008,81909,1586,"BENIGN, DoS slowloris, DoS Slowhttptest, DoS H..."

In [30]:
df.duplicated().sum()

np.int64(26935)